"""
Type stubs for spaCy CLI module.

This file helps Pylance understand the interface of spaCy's CLI tools.
"""

from typing import (
    Any,
    Callable,
    Dict,
    Iterator,
    List,
    Optional,
    Set,
    Tuple,
    Type,
    Union,
)

def download(model: str, direct: bool = False, *args: Any, **kwargs: Any) -> None: ...
def info(*args: Any, **kwargs: Any) -> None: ...
def package(*args: Any, **kwargs: Any) -> None: ...
def train(*args: Any, **kwargs: Any) -> None: ...
def evaluate(*args: Any, **kwargs: Any) -> None: ...
def convert(*args: Any, **kwargs: Any) -> None: ...
def init_model(*args: Any, **kwargs: Any) -> None: ...
def link(*args: Any, **kwargs: Any) -> None: ...
def profile(*args: Any, **kwargs: Any) -> None: ...
